# Generated by Django 5.2.8 on 2025-11-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=50)),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredientes', models.TextField(help_text='Lista de ingredientes separados por coma')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_preparacion', models.IntegerField(default=0, help_text='Tiempo en minutos')),
                ('dificultad', models.CharField(choices=[('fácil', 'fácil'), ('media', 'media'), ('difícil', 'difícil')], default='fácil', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
