# Generated by Django 5.0.14 on 2025-11-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receta",
            options={"verbose_name": "Receta", "verbose_name_plural": "Recetas"},
        ),
        migrations.AlterField(
            model_name="receta",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("sopa", "Sopa"),
                    ("carne", "Carne"),
                    ("ensalada", "Ensalada"),
                    ("postre", "Postre"),
                    ("bebida", "Bebida"),
                    ("otros", "Otros"),
                ],
                default="otros",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="dificultad",
            field=models.CharField(
                choices=[
                    ("fácil", "Fácil"),
                    ("media", "Media"),
                    ("difícil", "Difícil"),
                ],
                default="fácil",
                max_length=20,
            ),
        ),
    ]
